### ISSUE TITLE
The source code in the repository is incomplete

### ISSUE THREAD

**Issue by davidschreiber** [hsz/idea-latex#10]
I wanted to check out the plugin code and see if I can contribute to this project (since writing LaTeX in IntelliJ would be freaking awesome) but it seems that you have not published the complete source code to GitHub.

Is this by intention or did you miss out some files while committing? For example the `mobi.hsz.idea.latex.psi.LatexTypes` class is missing – and as far as I can see there are other classes missing as well.

**Comment by davidschreiber** [comment]
I count 15 missing Java files 

![Missing Java files.](https://cloud.githubusercontent.com/assets/1101857/7401614/dc67ebe4-eec5-11e4-8013-8ab483a80c92.png)

**Comment by hsz** [comment]
@davidschreiber Thank you for reporting.

Those files are automatically generated by the IntelliJ BNF/JFlex plugins and that's why they are not attached with the source code.

Anyway they should be generated into the `gen/` directory, not `src/`.

Currently doc is not updated, but the same process is described in my `idea-gitignore` project:

https://github.com/hsz/idea-gitignore#compiling-the-source-code
