### ISSUE TITLE
Ongoing development

### ISSUE THREAD

**Issue by JaegerP** [hsz/idea-latex#32]
Hi there,
is this an ongoing project? If so, I'd like to contribute. I've never programmed IDEA plugins before, so I'd likely need someone to ask questions while getting started...
Cheers

**Comment by tjysdsg** [comment]
There doesn't seem to be many latex plugins for IDEA, so it would be really great if this project can continue to update!

**Comment by wusatosi** [comment]
I do not think this project is under active development, the latest pull request (#28 ) has not received any updates from the original author since 2017.

I think there are two options for you,
- Contact the original author [hsz](https://github.com/hsz) if he is still interested in this project. It seems he is still active on Github, and his email address is shown on [his website](https://hsz.mobi/)
- Fork the project and develop it under your own repo

@hsz 

Hope this helps

**Comment by EzAccount** [comment]
I’ve contacted the original author — waiting for an answer.
I’m planning to work on the plugin, we can group together.

**Comment by VijoPlays** [comment]
I suppose it'd be best if someone were to fork it and just continue from there, seeing as there aren't any updates incoming and (unless @EzAccount got any update from hsz) the project is basically dead.

If someone does continue working on it (since many Forks are also just forked and never worked on), just comment on this issue, or create a new one, I suppose.

**Comment by EzAccount** [comment]
I think at this point LaTeX plugins are not so popular and OverLeaf is taking over. And I think they will release an app (electron based probable) which will cut a lot of use cases. For me it's at least more like a comfortable text editor and to write stuff while I code.
The hard-core geeks will stay with just a text editor (vim/emacs/..) and git/svn, but mostly people will switch I think. 
Just my opinion, since Overleaf is becoming an academia standard for good or for bad.

**Comment by hsz** [comment]
Sorry, folks – I needed 6 years to make up my mind and decide to close this project. 😅
I've removed LaTeX from the Marketplace and archived this repository. Thanks for the support, but I am not the right person to work on the LaTeX – I'm simply not using it, and I have no knowledge about how it works regarding more complex cases.
In the meantime, some other plugins appeared in the Marketplace with much more to offer – I bet they'll appreciate your feedback and contributions very much!
Thanks!
Jakub Chrzanowski
